source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

target 'base' do
    
    pod 'MJRefresh'
    pod 'Masonry'
    pod 'DZNEmptyDataSet'
    pod 'UITableView+FDTemplateLayoutCell'     # UITableViewCell 自动高度计算，缓存
    pod 'FDFullscreenPopGesture'
    pod 'IQKeyboardManager'

end
